### ISSUE TITLE
Support for Python 3.5

### ISSUE THREAD

**Issue by WritingPanda** [bbatsche/Ansible-Python-Site-Role#1]
Newer versions of Ubuntu will have Python 3.5. Fedora, I believe, will have the same. I doubt that CentOS will have Python 3.5 any time soon, but I could be mistaken. 

How about your support our brothers in Python and offer support for Python 3.5?

**Comment by bbatsche** [comment]
My goal is to target current LTS releases of Ubuntu, so when Xenial comes out I will add support for whichever versions of python are available there. At this point, to add the ability to install other versions of would involve some re-architecting of the install process and I don't see it adding the most value for my time.

PS - If you're interested in being able to run any arbitrary version of your application server software, perhaps you should look at the Ruby/Rbenv role I just finished. ;-)
