### ISSUE TITLE
Lazy loading of virtualenvwrapper

### ISSUE THREAD

**Issue by WritingPanda** [bbatsche/Ansible-Python-Site-Role#2]
The preferred way of doing it is not with the `virtualenvwrapper_lazy.sh`. Use `virtualenvwrapper.sh` with this command: `source /usr/local/bin/virtualenvwrapper.sh`.

**Comment by bbatsche** [comment]
Thanks! I will swap this in soon.

(I feel like I opted for `_lazy` because that seemed to be what Ubuntu did by default? To be frank, I'm not 100% clear on the difference between the two anymore)

**Comment by WritingPanda** [comment]
I think the big difference between the two is tab autocompleting. With lazy, the tab autocomplete will not begin unless the first command is run. I guess that is why they call it lazy. "Okay, fine. I'll start working now. Jeez."
